
def mensaje():
    print('+---------------------------------------------------------------------+')
    print('|                                                       Febrero 2023  |')
    print('|                                                       Honda,Tolima  |')
    print('|  Querida Helen,                                                     |')
    print('|                                                                     |')
    print('|      Quiero decirte en este dia no especial, que eres una persona   |')
    print('|      muy especial para mi, me gusta pasar el tiempo contigo y       |')
    print('|      molestarte se a vuelto un habito.                              |')
    print('|      Gracias por soportarme y ser tan bonita conmigo                |')
    print('|      Quiero estar contigo hasta donde se pueda y mientras tanto     |')
    print('|      tratar de superarnos y ser mejores personas cada dia, quiero   |')
    print('|      tener por mucho mas tiempo.                                    |')
    print('|      No quiero perderte chiquita.                                   |')
    print('|                                              De:                    |')
    print('|                                              Felipe Lenis           |')
    print('|                                                                     |')
    print('+---------------------------------------------------------------------+')
mensaje()
